moving php app folder

diff --git a/build b/build
--- a/build
+++ b/build
@@ -5,6 +5,10 @@ eval $(docker-machine env -u)
 
 # Update submodules (php, go ...)
 git submodule update --recursive --remote
+if [ $? != 0 ]; then
+    printf "\n\n GIT FAIL \n\n"
+    exit 1
+fi
 
 # Build All
 docker-compose -f config/compose.common.json -f config/compose.development.json -p xmp build
