InstId

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,14 +1,11 @@
 #!/usr/bin/env bash
 
-# Reset to local docker
-eval $(docker-machine env -u)
-
 # Update submodules (php, go ...)
-git submodule update --recursive --remote
-if [ $? != 0 ]; then
-    printf "\n\n GIT FAIL \n\n"
-    exit 1
-fi
+#git submodule update --recursive --remote
+#if [ $? != 0 ]; then
+#    printf "\n\n GIT FAIL \n\n"
+#    exit 1
+#fi
 
 # Build All
 docker-compose -f compose.json -p xmp build
